// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserHome() {
  return window['go']['main']['App']['GetUserHome']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadAppState() {
  return window['go']['main']['App']['LoadAppState']();
}

export function LoadCharacterCard(arg1) {
  return window['go']['main']['App']['LoadCharacterCard'](arg1);
}

export function LoadTemplateSchema(arg1) {
  return window['go']['main']['App']['LoadTemplateSchema'](arg1);
}

export function ResetAppState() {
  return window['go']['main']['App']['ResetAppState']();
}

export function SaveAppState(arg1) {
  return window['go']['main']['App']['SaveAppState'](arg1);
}

export function SaveBlankTemplate(arg1) {
  return window['go']['main']['App']['SaveBlankTemplate'](arg1);
}

export function SaveCharacterCard(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacterCard'](arg1, arg2);
}
