// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function GetUserHome():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadAppState():Promise<models.AppState>;

export function LoadCharacterCard(arg1:string):Promise<main.CharacterCard>;

export function LoadTemplateSchema(arg1:string):Promise<models.LayoutTemplate>;

export function ResetAppState():Promise<void>;

export function SaveAppState(arg1:any):Promise<void>;

export function SaveBlankTemplate(arg1:string):Promise<void>;

export function SaveCharacterCard(arg1:string,arg2:main.CharacterCard):Promise<void>;
